### ISSUE TITLE
Why is 1.0.0 advertised as the latest version on the GitHub Actions Marketplace?

### ISSUE THREAD

**Issue by pquentin** [tibdex/backport#108]
Currently, https://github.com/marketplace/actions/backporting shows 1.0.0:

![image](https://github.com/tibdex/backport/assets/42327/c98a4d0b-76ba-4c74-af39-4a4c6ef28e2e)

I would expect 2.0.4 instead. Thanks!

**Comment by JackPGreen** [comment]
![image](https://github.com/tibdex/backport/assets/8626721/2c2c58a0-8470-4e64-aa4e-a5df2dab2714)

Looks correct to me.

**Comment by pquentin** [comment]
Thanks! It is now
