### ISSUE TITLE
Creating multiple backports at once

### ISSUE THREAD

**Issue by m-kuhn** [tibdex/backport#17]
I just discovered this app and already love it.

It seems that currently it's only possible to do a single backport. We maintain multiple stable branches but specifying multiple labels only opens one backport. Would it be possible to have several backports ( like `backport release-3_4` and `backport release-3_6`)?

**Comment by tibdex** [comment]
Yup I agree that it should work. I'll fix it.

**Comment by m-kuhn** [comment]
Thanks for the feedback.
I guess you have already noticed that I opened #18 which should fix this.
