### ISSUE TITLE
Bogus Travis-CI and AppVeyor builds

### ISSUE THREAD

**Issue by rouault** [tibdex/backport#21]
https://github.com/OSGeo/proj.4/pull/1334 has been generated from a Backport label. One weird thing is that this pull request generates 2 Travis-CI and 2 AppVeyor builds. One of them is correct  "Travis CI - Pull Request"), but there's a bogus one "Travis CI - Branch" (https://github.com/OSGeo/proj.4/pull/1334/checks?check_run_id=80744998) which operates on  a branch `cherry-pick-backport-1333-on-6.0-16bdb30b-547c-4c9a-8115-d0a00515f983` that Travis-CI can't find. The same for `continuous-integration/appveyor/branch`

**Comment by tibdex** [comment]
Hi Even, you can see this similar issue on another repo: https://github.com/tibdex/autorebase/issues/15#issue-362600879

**Comment by rouault** [comment]
I've been pointed by other people about a workaround that I've integrated in my .travis.yml / appveyor.yml : https://github.com/OSGeo/gdal/commit/0b0160fb59757092b2b2bce4d8c253c6341e3b9e#diff-354f30a63fb0907d4ad57269548329e3

**Comment by tibdex** [comment]
Yup, that's similar to what https://github.com/tibdex/autorebase/issues/15#issuecomment-472116509 suggests.
