### ISSUE TITLE
Add a label to failed backports

### ISSUE THREAD

**Issue by galak** [tibdex/backport#29]
It would be nice to have a label added to any PR that the backport failed on.  Makes it easier to see PRs that need to be handled by hand.

**Comment by tibdex** [comment]
This would mean that Backport would automatically add its labels to the list of available ones. Right now this is not needed: its the repo maintainers that are in control of the `backport` labels they use. I would prefer to keep it this way.

What you can do instead is use the GitHub search and look for "backport failed".
