### ISSUE TITLE
propagate labels from original PR to backport PR

### ISSUE THREAD

**Issue by galak** [tibdex/backport#30]
It would be nice if the labels on the original PR get propagated to the backport PR (outside of the `backport-<BRANCH>` label).

**Comment by tibdex** [comment]
Hi @galak, I will make the same answer as the one I posted here: https://github.com/tibdex/github-backport/pull/6#issuecomment-478262279:

I would prefer not to duplicate all the labels of the original body to the backported PR.

The link to the original PR and the repetition of its title is IMO the right balance between enough context and too much duplication.
