### ISSUE TITLE
Clarification: Building and running the bot

### ISSUE THREAD

**Issue by heiko-braun** [tibdex/backport#37]
Apologies for my newbie question, but I am really unfamiliar with the node.js ecosystem. How do you build and run the bot during development and in production? 

I have tried `probot run` and the likes, but it seems that the backport.js is not picked up. The probot framwork comes up, but the hooks are not registered. 

I guess that I am doing something wrong between the typescript compile and launching the app in development.

Any tips would be greatly appreciated.

**Comment by tibdex** [comment]
Hi Heiko, since https://github.com/tibdex/backport/commit/ce3759ca5d2088e5dcaf6e6e506c92b3995daf61, this project is not using Probot anymore.
