### ISSUE TITLE
Question: backporting via Github's API or via file system (git clone)

### ISSUE THREAD

**Issue by sqren** [tibdex/backport#47]
Hey,

I was super impressed by [your project](https://github.com/tibdex/github-backport) that could backport a commit via Github's API without ever cloning the repo in question. For huge git repos that can take minutes to clone, this is pretty amazing.
I'm curious why you didn't use this approach for this Github Action. Did you run into problems with that approach or was it just not worth it?

Although not perfect an issue seemed like the best format for this kind of question. But feel free to close as "off-topic" if you want. No hard feelings ;)

**Comment by tibdex** [comment]
Hi @sqren, `github-backport` works OK and indeed can be the best solution for huge git repos. However it has these drawbacks:
- It requires more than `2 * n` requests on the GitHub API where `n` is the number of commits to backport so rate limiting can become an issue.
- It creates multiple temporary branches on the repo and they can trigger unwanted CI builds.
- The underlying cherry-picking is not as good as the one offered by the Git CLI (See https://github.com/tibdex/github-cherry-pick/issues/9). So it feels a bit like reinventing the wheel but ending with something a bit worse in some ways.

**Comment by sqren** [comment]
Makes sense. Thanks for taking the time. 
Closing
