### ISSUE TITLE
Rebase and Merge with mulitple commits

### ISSUE THREAD

**Issue by carlescufi** [tibdex/backport#48]
Thanks for the action!

Is there a reason why PRs with multiple commits are not supported when they've been Rebased and Merged, or just that you haven't needed it so far?

**Comment by tibdex** [comment]
Hi carles, see https://github.com/tibdex/backport/issues/34#issuecomment-558976504. I always use "Squash and merge" so I do not need to support multiple commits.

**Comment by carlescufi** [comment]
Thanks @tibdex. Would you accept a PR implementing this?

**Comment by carlescufi** [comment]
Sounds good @tibdex, thanks for the feedback.

**Comment by carlescufi** [comment]
@tibdex I know you mentioned you'd rather not, but if I may I will just paste here a link to a commit that enables the backport action with multiple commits in the rebase and merge strategy. The change is minimal, so I wonder if you'd consider it for your tree. If you don't then I will just use my fork:

https://github.com/carlescufi/backport/commit/03c12470c6fee26498f2e4c42fdc44131d8e851b

Thanks.
