### ISSUE TITLE
Backport PRs need to be closed and reopened to trigger CI

### ISSUE THREAD

**Issue by pmalek-sumo** [tibdex/backport#61]
We're using this action in our pipeline https://github.com/SumoLogic/sumologic-kubernetes-collection/blob/main/.github/workflows/backport_bot.yaml and it is saving us a ton of work but one minor thing that we're struggling with is that the backport PRs need to be closed and reopened to trigger other Github Actions pipelines.

Is this a problem with our usage or this action?

Before reopening:

![image](https://user-images.githubusercontent.com/69143962/109631998-da942080-7b46-11eb-81f2-66f3f05127d3.png)

After

![image](https://user-images.githubusercontent.com/69143962/109632081-f4356800-7b46-11eb-863a-d814bec7b766.png)

**Comment by tibdex** [comment]
Hi Patryk, this looks similar to [this](https://github.com/tibdex/autosquash/blob/17fa441faea2c28da8c0dbad1156c7709e93b96d/.github/workflows/autosquash.yml#L27-L33).

**Comment by pmalek-sumo** [comment]
So I'm trying to use https://github.com/tibdex/github-app-token but I'm still trying to wrap my head around what app credentials (ID and PRIVATE_KEY) do I need to provide in action's config?

Do I need to create an app in my org and ... implement authorization and all that?

**Comment by tibdex** [comment]
You can take some inspiration from https://docs.github.com/en/issues/trying-out-the-new-projects-experience/automating-projects#example-workflow-authenticating-with-a-github-app.
