### ISSUE TITLE
Feature: Copy labels from original PR

### ISSUE THREAD

**Issue by travisgroth** [tibdex/backport#64]
Hi - It would be really helpful if the labels from the original PR (minus the backport label) were copied to the new PR.  We use labels to build our changelogs and have to remember to manually re-label anything backported before merging.

**Comment by tibdex** [comment]
It's this:

https://github.com/tibdex/backport/blob/b1bb2aaf611d9f2e5d1900c06493769b9f102a45/action.yml#L32-L39

**Comment by vmohir** [comment]
@tibdex Thanks but I'm confused how it's working. I've tried `labels_template: <%= labels %>` and `labels_template: '[<%= labels %>]'` and it says `Could not parse labels from invalid JSON`. Should I use something like `labels_template: "<% _.forEach(labels, function(label) { %><%- label %><% }); %>"`?
