### ISSUE TITLE
Clarification: backported to the target branch or to a temporary branch?

### ISSUE THREAD

**Issue by benipeled** [tibdex/backport#82]
According to the [usage](https://github.com/tibdex/backport#usage) section on the README: 

> That's it! When the pull request gets merged, it will be backported to the production branch. If the pull request cannot be backported, a comment explaining why will automatically be posted.

This means (AFAIU) that PRs merged to the master branch with the label `backport production` should be auto backported to a branch name `production`, but what seems to be happening in practice is that the PR is merged to a temporary branch, named `backport-<pr_no>-to-production`,

Am I missing something? is it on purpose?
It would be great if the PR auto backport directly into the production branch (or any other branch according to the `backport <branch>` format)

**Comment by tibdex** [comment]
> what seems to be happening in practice is that the PR is merged to a temporary branch, named backport-<pr_no>-to-production

Yes the action is designed this way: it opens a PR that can be reviewed and CI-checked before being merged. Often, the PR's head branch (the branch on which you want to backport) will have some branch protections preventing to push on it without going through a PR first.

You could use another action to automatically merge the PRs created by this `backport` action if that's what you want.
