### ISSUE TITLE
Issue: Rebase and merge pull requests with multiple commits and "rebase and merge"

### ISSUE THREAD

**Issue by kikito** [tibdex/backport#98]
This action seems to not handle correctly the cases where:
* a pull request has multiple commits
* it is merged with "rebase and merge"

The expected output is that the backport pr would have the same commits as the original PR.

What we are seeing is that the backport only contains one of the commits from the original PR instead.

**Comment by tibdex** [comment]
Yes this is mentioned in the README:

https://github.com/tibdex/backport/blob/b1bb2aaf611d9f2e5d1900c06493769b9f102a45/README.md#L3
